### PR TITLE
test: added mockito modular integration tests

### PR DESCRIPTION
**Pull request by TomerFi**
Signed-off-by: Tomer Figenblat <tomer@tomfi.info>

[v5.0.0](https://github.com/mockito/mockito/releases/tag/v5.0.0) was a milestone release for Mockito.
The default mock maker was replaced from `mock-subclass` to `mock-inline`.

Unfortunately, this broke this plugin.

This PR doesn't fix anything, rather it introduces two identical modular integration tests.
One running the current latest v4.x version, [v4.11.0](https://github.com/mockito/mockito/releases/tag/v4.11.0) and **executes successfully**.
And one running the current latest v5.x version [v.5.3.1](https://github.com/mockito/mockito/releases/tag/v5.3.1) and **fails**.
Throwing exceptions in regards to the `mock maker` creation and `bytebuddy`.

Looking into [mockito's issues](https://github.com/mockito/mockito/issues?q=is%3Aissue+Could+not+initialize+inline+Byte+Buddy+mock+maker), it doesn't look like we're the only ones experiencing this.
It is not yet clear if it's a `mockito` issue, a `bytebuddy` issue, a `java` version issue, or simply some tweaking of the `module-info.test` is required. Might even be something we need to change on the plugin end.
Regardless, these integration tests should be merged once this is resolved.

> Mockito v5.3.1 is used in the integration tests. But I verified on my end this break starts with version 5.0.0.

### CODE REVIEW

**Comment by TomerFi** [comment]
I pasted the logs [here](https://pastebin.com/JC5KFRiN).

**Comment by sormuras** [comment]
> I pasted the logs [here](https://pastebin.com/JC5KFRiN).

_Forbidden (#403)_
_Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it._

Can you make it public or paste it here?

**Comment by TomerFi** [comment]
> > I pasted the logs [here](https://pastebin.com/JC5KFRiN).
> 
> _Forbidden (#403)_ _Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it._
> 
> Can you make it public or paste it here?

I can't, it's too big.
I shared it using my Drive instead:

https://drive.google.com/file/d/1fq6e9Yz7EUKbsxvM-TWCpZFOQehmyYlI/view?usp=sharing

**Comment by sormuras** [comment]
Seems to be an issue by/with Mockito 5. Maybe @raphw can give us a hint? 🤔

**Comment by raphw** [comment]
The root cause is "java.lang.IllegalStateException: No compatible attachment provider is available". Mockito cannot self-attach. Is the VM set up to disallow this?

**Comment by TomerFi** [comment]
Looks like we get the same result when using attaching with Mockito 4 as well.
I'll add a test demonstrating this.

**Comment by TomerFi** [comment]
I added a third integration test, current status is, the _mockito-modular-v4-subclass_ test works, but _mockito-modular-v4-attach_ and _mockito-modular-v5-attach_ fail.

**Comment by raphw** [comment]
Is this a modular test? Is the jdk.attach module missing, possibly?

**Comment by sormuras** [comment]
> Is this a modular test?

Yes.

Looking at the configuration in a minute ... does Mockito ship with a module descriptor? If yes, does it `require jdk.attach;`?

**Comment by sormuras** [comment]
Your guess was spot on, Rafael. 👍

**Review by sormuras — APPROVED** [review]
With adding `jdk.attach` to the list of modules in `--add-modules` of the `module-info.test` files these three integration tests are green.

**Comment by raphw** [comment]
I tried adding a module to Mockito:
```java
module org.mockito {
    requires net.bytebuddy;
    requires net.bytebuddy.agent;
    requires java.instrument;
    requires jdk.attach;
    requires static junit;
    requires static org.opentest4j;
    requires static org.hamcrest;
    exports org.mockito;
    exports org.mockito.configuration;
    exports org.mockito.creation.instance;
    exports org.mockito.exceptions.base;
    exports org.mockito.exceptions.misusing;
    exports org.mockito.exceptions.stacktrace;
    exports org.mockito.exceptions.verification;
    exports org.mockito.invocation;
    exports org.mockito.junit;
    exports org.mockito.listeners;
    exports org.mockito.mock;
    exports org.mockito.plugins;
    exports org.mockito.quality;
    exports org.mockito.session;
    exports org.mockito.stubbing;
    exports org.mockito.verification;
}
```
It fails the compilation, unfortunately, but if you find the time to look into it, we accept a PR happily.

**Comment by sormuras** [comment]
What I tried (on a GH Codespace instance) in order after adding the module descriptor you proposed to `src/main/java/module-info.java`:

- [ ] `build`  ... _Gradle daemon died_
- [x] `compileJava` 🥳 
- [ ] `test` ... _fails with 3+ erros_ _Gradle daemon died_

I didn't make it to `javadoc` so far...

```
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=113b2f7e-a967-4abb-89d2-48cbe394bcc6, currentDir=/workspaces/mockito}
Attempting to read last messages from the daemon log...
Daemon pid: 13178
  log file: /home/codespace/.gradle/daemon/7.6/daemon-13178.out.log
----- Last  20 lines from daemon log file - daemon-13178.out.log -----
        at org.mockito.internal.MockitoCore.mock(MockitoCore.java:88)
        at org.mockito.Mockito.mock(Mockito.java:2102)
        at org.mockitousage.basicapi.MocksSerializationForAnnotationTest.should_serialize_with_real_object_spy(MocksSerializationForAnnotationTest.java:284)
...
* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
```

**Comment by raphw** [comment]
Strange. Remember to setup Java 11 and then *gradlew build*. The only difference in the javadoc options that I can spot is that *module-path* is used instead of *classpath*, leading the the failures.

**Comment by sormuras** [comment]
FYI: I just disabled two of the three modular Mockito tests - if you have some extra cycles, please take a look at #114 Merci!

**Comment by raphw** [comment]
Those are tests with modules that fail when Mockito is used?

**Comment by sormuras** [comment]
Yeah. Here's an interesting snippet of the log:

```
[ERROR] Underlying exception : org.mockito.exceptions.base.MockitoException: 
[ERROR] Could not force module adjustment of the module of interface mockitov4subclass.AppInterface
[ERROR] 
[ERROR] This is required to adjust the module graph to enable mock creation
[ERROR]        org.mockito.junit.jupiter@4.11.0/org.mockito.junit.jupiter.MockitoExtension.beforeEach(MockitoExtension.java:153)
[ERROR]        java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[ERROR]        java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[ERROR]        Suppressed: java.lang.NullPointerException: Cannot invoke "java.util.Set.forEach(java.util.function.Consumer)" because the return value of "org.junit.jupiter.api.extension.ExtensionContext$Store.remove(Object, java.lang.Class)" is null
[ERROR]          org.mockito.junit.jupiter@4.11.0/org.mockito.junit.jupiter.MockitoExtension.afterEach(MockitoExtension.java:184)
[ERROR]          [...]
[ERROR]      Caused by: org.mockito.exceptions.base.MockitoException: 
[ERROR] Could not force module adjustment of the module of interface mockitov4subclass.AppInterface
[ERROR] 
[ERROR] This is required to adjust the module graph to enable mock creation
[ERROR]        net.bytebuddy@1.12.19/net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
[ERROR]        net.bytebuddy@1.12.19/net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
[ERROR]        net.bytebuddy@1.12.19/net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
[ERROR]        net.bytebuddy@1.12.19/net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
[ERROR]        [...]
[ERROR]      Caused by: java.lang.IllegalArgumentException: mockitov4subclass.AppInterface$MockitoModuleProbe$mq2k4v2qnbbf13 must be defined in the same package as org.mockito.codegen.InjectionBase
[ERROR]        net.bytebuddy@1.12.19/net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1635)
[ERROR]        net.bytebuddy@1.12.19/net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118)
[ERROR]        net.bytebuddy@1.12.19/net.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:519)
[ERROR]        net.bytebuddy@1.12.19/net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
[ERROR]        net.bytebuddy@1.12.19/net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6317)
[ERROR]        [...]
```

**Pull request merged**
