### PR TITLE
fix: remove stdout line limit in java executor and switch to lines api

### PR DESCRIPTION
**Pull request by TomerFi**
fixes: #90

### CODE REVIEW

**Review by sormuras — APPROVED** [review]
LGTM

**Comment by TomerFi** [comment]
@sormuras 
Thank you!

Perhaps we do a new release?
The new release will include not only this but also the tags issue.

**Comment by sormuras** [comment]
> Perhaps we'll make a new release?

Sure. I'm on it...

**Comment by sormuras** [comment]
Done.

Thanks for your contributions, Tomer!

**Comment by TomerFi** [comment]
Thank you for this amazing plugin.
I can't even remember how to work without it.
😃

**Pull request merged**
