### PR TITLE
Handle multi modules where one reactor project has no tests

### PR DESCRIPTION
**Pull request by TomerFi**
Added integration test as ﻿a follow up for [this discussion](https://github.com/sormuras/junit-platform-maven-plugin/discussions/74).

Notes:

- The prebuild and verifier scripts were written in `groovy`.
  To avoid the wrong version popping up, I've added the groovy dependency to the invoker plugin configuration.
  If this is not cool, I'll go back to `beanshell` and force push.

- The integration test currently fails, as expected.
  For the record, removing the `module-info` descriptors, makes it pass.

- There's a TODO comment in the verifier script, as a reminder to add log verifications.
  I will handle it once we get this integration test to pass.

### CODE REVIEW

**Comment by sormuras** [comment]
> The prebuild and verifier scripts were written in groovy.

That's cool and ... groovy.

Is the prebuild check a standard feature of the invoker plugin? 🤔

```text
[INFO] Building: modular-multi-modules-no-tests/pom.xml
[INFO] run pre-build script prebuild.groovy
[INFO] run post-build script verify.groovy
[INFO]   The post-build script returned false.
[INFO]           modular-multi-modules-no-tests/pom.xml ........... FAILED (5.3 s)
```

Yes, it is. Learned something new today.

Let's fix this on your branch and we're good to merge.

**Comment by TomerFi** [comment]
@sormuras 
Fixed it, now the test passes.
:-)

**Comment by sormuras** [comment]
> Please don't merge this yet, I want to handle that TODO comment prior to merging.

Awaiting your "Go!" then.

**Comment by TomerFi** [comment]
> Awaiting your "Go!" then.

@sormuras Go! :smiley:

**Comment by sormuras** [comment]
Gone. 🚀

**Pull request merged**
