### PR TITLE
fix: get elements from test classpath and not runtime or compile

### PR DESCRIPTION
**Pull request by TomerFi**
Continuation of https://github.com/sormuras/junit-platform-maven-plugin/discussions/78 .

### CODE REVIEW

**Comment by sormuras** [comment]
> Error:  The following builds failed:
> Error:  *  classloader-isolation/pom.xml

...that's why I expected to happen earlier with #76 - but that change worked out nicely.

Using `project.getTestClasspathElements()` adds too many elements, especially some that should only be available in `test` scope.

**Comment by TomerFi** [comment]
> > Error:  The following builds failed:
> > Error:  *  classloader-isolation/pom.xml
> 
> ...that's what I expected to happen earlier with #76 - but that change worked out nicely.
> 
> Using `project.getTestClasspathElements()` adds too many elements, especially some that should only be available in `test` scope.

I think we should either use both [getCompileClasspathElements](https://maven.apache.org/ref/3.8.1/apidocs/org/apache/maven/project/MavenProject.html#getCompileClasspathElements--) and [getRuntimeClasspathElements](https://maven.apache.org/ref/3.8.1/apidocs/org/apache/maven/project/MavenProject.html#getRuntimeClasspathElements--),
Or maybe try to work with [getDependencies](https://maven.apache.org/ref/3.8.1/apidocs/org/apache/maven/project/MavenProject.html#getDependencies--) I'm looking into it a little bit more.

What are your thoughts on this manner?

**Comment by TomerFi** [comment]
@sormuras now the test passes, after including all the test elements within the `testPaths` set.

But, maybe that's not enough?
Maybe we should include the compile and/or runtime dependencies in the `mainPaths` set regardless.

**Comment by TomerFi** [comment]
Hmm...
That doesn't look OK.
I haven't noticed that the same addition to the set exists a couple of lines later.
Which means that removing the original line, haven't failed any tests.

I think we should go back to the idea of adding both compile and runtime dependencies to the main classloader and tests to verify the case.

**Comment by TomerFi** [comment]
Here we go.

Eventually, I've added the compile dependencies to the mainPaths set alongside the runtime dependencies.
I've also added an integration test verifying this.

**Pull request merged**
