### PR TITLE
fix: fixed tags and params for the java executor

### PR DESCRIPTION
**Pull request by TomerFi**
fixes: #84

### CODE REVIEW

**Comment by sormuras** [comment]
Space characters aren't a thing in property names nor in tag names, aye?

**Comment by TomerFi** [comment]
It works well without it.

**Review by sormuras — APPROVED** [review]
LGTM

**Comment by sormuras** [comment]
Feel free to merge such good fixes every time, Tomer!

**Comment by TomerFi** [comment]
Thank you very much!
I don't think I have merge access.
😁

**Comment by TomerFi** [comment]
Thank you very much!
 😃

**Comment by sormuras** [comment]
You're welcome. 🤓

**Pull request merged**
